# base16 Precious Light White - alacritty color config
# 4lex4 &lt;4lex49@zoho.com&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x555555'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x555555'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xaf4947'
green = '0x557301'
yellow = '0x876500'
blue = '0x186daa'
magenta = '0x7b4ecb'
cyan = '0x087767'
white = '0x555555'

# Bright colors
[colors.bright]
black = '0xdbdbdb'
red = '0xa0570d'
green = '0xededed'
yellow = '0xdbdbdb'
blue = '0x636363'
magenta = '0x555555'
cyan = '0xa93e93'
white = '0x555555'
