# base24 Framer - alacritty color config
# FredHappyface (https://github.com/fredHappyface)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x111111'
foreground = '0xa9a9a9'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x111111'
cursor = '0xa9a9a9'

# Normal colors
[colors.normal]
black = '0x111111'
red = '0xff5555'
green = '0x98ec65'
yellow = '0x33bbff'
blue = '0x00aaff'
magenta = '0xaa88ff'
cyan = '0x88ddff'
white = '0xa9a9a9'
#
# Bright colors
[colors.bright]
black = '0x414141'
red = '0xff8888'
green = '0xb6f292'
yellow = '0xffd966'
blue = '0x33bbff'
magenta = '0xcebbff'
cyan = '0xbbecff'
white = '0xffffff'

