# base24 Brogrammer - alacritty color config
# FredHappyface (https://github.com/fredHappyface)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x131313'
foreground = '0xc1c8d7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x131313'
cursor = '0xc1c8d7'

# Normal colors
[colors.normal]
black = '0x131313'
red = '0xf71118'
green = '0x2cc55d'
yellow = '0x0f80d5'
blue = '0x2a84d2'
magenta = '0x4e59b7'
cyan = '0x0f80d5'
white = '0xc1c8d7'
#
# Bright colors
[colors.bright]
black = '0x2a3141'
red = '0xde342e'
green = '0x1dd260'
yellow = '0xf2bd09'
blue = '0x509bdc'
magenta = '0x524fb9'
cyan = '0x289af0'
white = '0xffffff'

