# base24 One Dark - alacritty color config
# FredHappyface (https://github.com/fredHappyface)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x282c34'
foreground = '0xabb2bf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x282c34'
cursor = '0xabb2bf'

# Normal colors
[colors.normal]
black = '0x282c34'
red = '0xe05561'
green = '0x8cc265'
yellow = '0xe6b965'
blue = '0x4aa5f0'
magenta = '0xc162de'
cyan = '0x42b3c2'
white = '0xabb2bf'
#
# Bright colors
[colors.bright]
black = '0x4f5666'
red = '0xff616e'
green = '0xa5e075'
yellow = '0xf0a45d'
blue = '0x4dc4ff'
magenta = '0xde73ff'
cyan = '0x4cd1e0'
white = '0xffffff'

