# base16 OneDark Dark - alacritty color config
# olimorris (https://github.com/olimorris)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x000000'
foreground = '0xabb2bf'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x000000'
cursor = '0xabb2bf'

# Normal colors
[colors.normal]
black = '0x000000'
red = '0xef596f'
green = '0x89ca78'
yellow = '0xe5c07b'
blue = '0x61afef'
magenta = '0xd55fde'
cyan = '0x2bbac5'
white = '0xabb2bf'

# Bright colors
[colors.bright]
black = '0x2c313a'
red = '0xd19a66'
green = '0x1c1f24'
yellow = '0x2c313a'
blue = '0x565c64'
magenta = '0xb6bdca'
cyan = '0xbe5046'
white = '0xc8ccd4'
