# base16 Precious Light Warm - alacritty color config
# 4lex4 &lt;4lex49@zoho.com&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfff5e5'
foreground = '0x4e5359'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfff5e5'
cursor = '0x4e5359'

# Normal colors
[colors.normal]
black = '0xfff5e5'
red = '0xb14745'
green = '0x557300'
yellow = '0x876500'
blue = '0x246da5'
magenta = '0x7a50c6'
cyan = '0x0e7767'
white = '0x4e5359'

# Bright colors
[colors.bright]
black = '0xd9d3c8'
red = '0xa25600'
green = '0xece4d6'
yellow = '0xd9d3c8'
blue = '0x5d6065'
magenta = '0x4e5359'
cyan = '0xa83f92'
white = '0x4e5359'
