# base24 Deep Oceanic Next - alacritty color config
# spearkkk (https://github.com/spearkkk/deep-oceanic-next)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x003b46'
foreground = '0xdce3e8'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x003b46'
cursor = '0xdce3e8'

# Normal colors
[colors.normal]
black = '0x003b46'
red = '0xe6454b'
green = '0x85b57a'
yellow = '0xffcc66'
blue = '0x3a82e6'
magenta = '0x8c4de6'
cyan = '0x4da6a6'
white = '0xdce3e8'
#
# Bright colors
[colors.bright]
black = '0x006374'
red = '0xff5a61'
green = '0x99d8a0'
yellow = '0xffdd80'
blue = '0x4da6ff'
magenta = '0xa366ff'
cyan = '0x66cccc'
white = '0xf0f5f5'

