# base16 Terracotta Dark - alacritty color config
# Alexander Rossell Hayes (https://github.com/rossellhayes)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x241d1a'
foreground = '0xb8a59d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x241d1a'
cursor = '0xb8a59d'

# Normal colors
[colors.normal]
black = '0x241d1a'
red = '0xf6998f'
green = '0xb6c68a'
yellow = '0xffc37a'
blue = '0xb0a4c3'
magenta = '0xd8a2b0'
cyan = '0xc0bcdb'
white = '0xb8a59d'

# Bright colors
[colors.bright]
black = '0x473933'
red = '0xffa888'
green = '0x362b27'
yellow = '0x473933'
blue = '0xa78e84'
magenta = '0xcabbb5'
cyan = '0xf1ae97'
white = '0xdcd2ce'
