# base16 Everforest - alacritty color config
# Sainnhe Park (https://github.com/sainnhe)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2d353b'
foreground = '0xd3c6aa'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2d353b'
cursor = '0xd3c6aa'

# Normal colors
[colors.normal]
black = '0x2d353b'
red = '0xe67e80'
green = '0xa7c080'
yellow = '0xdbbc7f'
blue = '0x7fbbb3'
magenta = '0xd699b6'
cyan = '0x83c092'
white = '0xd3c6aa'

# Bright colors
[colors.bright]
black = '0x475258'
red = '0xe69875'
green = '0x343f44'
yellow = '0x475258'
blue = '0x9da9a0'
magenta = '0xe6e2cc'
cyan = '0x9da9a0'
white = '0xfdf6e3'
