# base16 Everforest Dark Hard - alacritty color config
# Sainnhe Park (https://github.com/sainnhe)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x272e33'
foreground = '0xd3c6aa'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x272e33'
cursor = '0xd3c6aa'

# Normal colors
[colors.normal]
black = '0x272e33'
red = '0xe67e80'
green = '0xa7c080'
yellow = '0xdbbc7f'
blue = '0x7fbbb3'
magenta = '0xd699b6'
cyan = '0x83c092'
white = '0xd3c6aa'

# Bright colors
[colors.bright]
black = '0x414b50'
red = '0xe69875'
green = '0x2e383c'
yellow = '0x414b50'
blue = '0x9da9a0'
magenta = '0xedeada'
cyan = '0x9da9a0'
white = '0xfffbef'
