# base16 Precious Dark Eleven - alacritty color config
# 4lex4 &lt;4lex49@zoho.com&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1c1e20'
foreground = '0xb8b7b6'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1c1e20'
cursor = '0xb8b7b6'

# Normal colors
[colors.normal]
black = '0x1c1e20'
red = '0xff8782'
green = '0x95b658'
yellow = '0xd0a543'
blue = '0x68b0ee'
magenta = '0xb799fe'
cyan = '0x42bda7'
white = '0xb8b7b6'

# Bright colors
[colors.bright]
black = '0x37393a'
red = '0xea9755'
green = '0x292b2d'
yellow = '0x37393a'
blue = '0xa8a8a7'
magenta = '0xb8b7b6'
cyan = '0xf382d8'
white = '0xb8b7b6'
